# -*- coding: utf-8 -*-
"""Copy of Menaga_A_cpda_10_Car_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cv_wmD-DTo1lxbKt22u1yPryAHSp-JZ6

Car Data Analysis Project
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()



# Load dataset

df_car_prices = pd.read_csv('/content/car_prices.csv')

# Display first 5 rows

df_car_prices.head()

df_car_prices.head()

df_car_prices = pd.read_csv('/content/car_prices.csv')

# Display first 5 rows

df_car_prices.head()

# Dataset Information

df_car_prices.info()

# Total number of records

len(df_car_prices)

# Shape of dataset

df_car_prices.shape

# Column names

df_car_prices.columns

# Data types of columns

df_car_prices.dtypes

# Count missing values

df_car_prices.isnull().sum()



# Bar chart for missing values

plt.figure(figsize=(12,6))

df_car_prices.isnull().sum().plot(kind='bar')

plt.title('Missing Values Per Column')

plt.xlabel('Columns')
plt.ylabel('Count of Missing Values')

plt.xticks(rotation=45)

plt.show()

#Heatmap for missing values

plt.figure(figsize=(12,6))

sns.heatmap(df_car_prices.isnull(), cbar=False)

plt.title('Missing Values Heatmap')

plt.show()

# Fill numerical null values with median

num_cols = ['condition', 'odometer', 'mmr', 'sellingprice']

for col in num_cols:
    df_car_prices[col].fillna(df_car_prices[col].median(), inplace=True)

# Fill categorical null values with mode

cat_cols = ['make', 'model', 'trim', 'body',
            'transmission', 'color',
            'interior', 'seller', 'state']

for col in cat_cols:
    df_car_prices[col].fillna(df_car_prices[col].mode()[0], inplace=True)

# Check missing values after treatment

df_car_prices.isnull().sum()

# Count duplicate records

df_car_prices.duplicated().sum()

# Remove duplicate records

df_car_prices.drop_duplicates(inplace=True)

# Verify duplicate removal

df_car_prices.duplicated().sum()

# Final cleaned dataset info

df_car_prices.info()

# Save cleaned dataset

df_car_prices.to_csv('cleaned_car_prices.csv', index=False)

"""## DataFrame Queries"""

# Average, Minimum and Maximum Selling Price

print("Average Car Price:", df_car_prices['sellingprice'].mean())

print("Minimum Car Price:", df_car_prices['sellingprice'].min())

print("Maximum Car Price:", df_car_prices['sellingprice'].max())

# Unique colors of cars

df_car_prices['color'].unique()

# Number of unique car brands

print("Unique Car Brands:", df_car_prices['make'].nunique())

# Number of unique car models

print("Unique Car Models:", df_car_prices['model'].nunique())

# Cars having selling price greater than 165000

high_price_cars = df_car_prices[df_car_prices['sellingprice'] > 165000]

high_price_cars

# Top 5 most frequently sold car models

df_car_prices['model'].value_counts().head(5)

# Average selling price by make

avg_price_by_make = df_car_prices.groupby('make')['sellingprice'].mean()

avg_price_by_make.sort_values(ascending=False)

# Minimum selling price for each interior

min_price_interior = df_car_prices.groupby('interior')['sellingprice'].min()

min_price_interior

# Highest odometer reading per year

highest_odometer = df_car_prices.groupby('year')['odometer'].max()

highest_odometer.sort_values(ascending=False)

# Create car_age column

df_car_prices['car_age'] = 2025 - df_car_prices['year']

# Display year and car age

df_car_prices[['year', 'car_age']].head()

# Filter cars based on condition and odometer

filtered_cars = df_car_prices[
    (df_car_prices['condition'] >= 48) &
    (df_car_prices['odometer'] > 90000)
]

# Count filtered cars

print("Number of Cars:", filtered_cars.shape[0])

# Filter newer cars

newer_cars = df_car_prices[df_car_prices['year'] > 2013]

# Average selling price by state

state_prices = newer_cars.groupby('state')['sellingprice'].mean()

# Sort from highest to lowest

state_prices.sort_values(ascending=False)

"""# Data Visualization"""

# Select numerical columns

numerical_columns = df_car_prices.select_dtypes(include=['int64', 'float64'])

# Correlation matrix

correlation_matrix = numerical_columns.corr()

# Plot heatmap

plt.figure(figsize=(10,8))

sns.heatmap(correlation_matrix,
            annot=True,
            cmap='coolwarm',
            fmt='.2f')

plt.title('Correlation Matrix of Numerical Features')

plt.show()

# Average selling price by year

avg_price_year = df_car_prices.groupby('year')['sellingprice'].mean()

# Plot

plt.figure(figsize=(14,6))

avg_price_year.plot(kind='bar')

plt.title('Average Selling Price by Year')

plt.xlabel('Year')

plt.ylabel('Average Selling Price')

plt.show()

#Scatter plot of odometer vs selling price

plt.figure(figsize=(10,6))

plt.scatter(df_car_prices['odometer'],
            df_car_prices['sellingprice'],
            alpha=0.5)

plt.title('Selling Price vs Odometer')

plt.xlabel('Odometer')

plt.ylabel('Selling Price')

plt.show()

"""As a car's mileage increases, its resale value typically decreases.s.

"""

# Cars sold by state

cars_by_state = df_car_prices['state'].value_counts()

# Plot

plt.figure(figsize=(15,6))

cars_by_state.plot(kind='bar')

plt.title('Number of Cars Sold by State')

plt.xlabel('State')

plt.ylabel('Number of Cars Sold')

plt.show()

# Top 3 car selling states

cars_by_state.head(3)

"""Larger populations and higher demand drive dominant car sales in specific states."""

# Create condition bins

df_car_prices['condition_range'] = pd.cut(
    df_car_prices['condition'],
    bins=range(0, 105, 5)
)

# Average price by condition range

avg_price_condition = df_car_prices.groupby(
    'condition_range'
)['sellingprice'].mean()

# Plot graph

plt.figure(figsize=(14,6))

avg_price_condition.plot(kind='bar')

plt.title('Average Selling Price by Condition Range')

plt.xlabel('Condition Range')

plt.ylabel('Average Selling Price')

plt.xticks(rotation=45)

plt.show()

# Create condition bins of size 10

df_car_prices['condition_range_10'] = pd.cut(
    df_car_prices['condition'],
    bins=range(0, 110, 10)
)

# Count cars by condition range

condition_counts = df_car_prices['condition_range_10'].value_counts().sort_index()

# Plot graph

plt.figure(figsize=(12,6))

condition_counts.plot(kind='bar')

plt.title('Number of Cars Sold by Condition Range')

plt.xlabel('Condition Range')

plt.ylabel('Number of Cars Sold')

plt.xticks(rotation=45)

plt.show()

"""Most cars are concentrated in medium to high condition ranges.
Very low-condition cars are less frequently sold.
"""

# Box plot of selling price by color

plt.figure(figsize=(15,6))

sns.boxplot(
    x='color',
    y='sellingprice',
    data=df_car_prices
)

plt.title('Selling Price Distribution by Color')

plt.xticks(rotation=90)

plt.show()

"""Car colors impact price stability, with high-end luxury vehicles in specific shades creating massive price outliers."""

# Calculate Q1 and Q3

Q1 = df_car_prices['sellingprice'].quantile(0.25)

Q3 = df_car_prices['sellingprice'].quantile(0.75)

# Calculate IQR

IQR = Q3 - Q1

# Lower and Upper Limits

lower_limit = Q1 - 1.5 * IQR

upper_limit = Q3 + 1.5 * IQR

# Remove outliers

df_no_outliers = df_car_prices[
    (df_car_prices['sellingprice'] >= lower_limit) &
    (df_car_prices['sellingprice'] <= upper_limit)
]

# Boxplot after removing outliers

plt.figure(figsize=(15,6))

sns.boxplot(
    x='color',
    y='sellingprice',
    data=df_no_outliers
)

plt.title('Selling Price Distribution by Color (Without Outliers)')

plt.xticks(rotation=90)

plt.show()

"""Insights

Vehicle Age: Newer model years consistently command premium pricing.

Usage Impact: Accumulated mileage acts as a primary driver of depreciation.

Geographic Trends: Used car market volume is heavily concentrated in a few key states.

Vehicle Condition: The physical and mechanical state of a car heavily dictates its market value.

Brand Volume: High consumer demand ensures certain manufacturers maintain a dominant market share.
"""

# Create dashboard

fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# ---------------------------------------------
# 1. Average Selling Price by Year
# ---------------------------------------------

avg_price_year = df_car_prices.groupby('year')['sellingprice'].mean()

avg_price_year.plot(
    kind='bar',
    ax=axes[0,0]
)

axes[0,0].set_title('Average Selling Price by Year')
axes[0,0].set_xlabel('Year')
axes[0,0].set_ylabel('Avg Selling Price')

# ---------------------------------------------
# 2. Cars Sold by State
# ---------------------------------------------

state_sales = df_car_prices['state'].value_counts().head(10)

state_sales.plot(
    kind='bar',
    ax=axes[0,1]
)

axes[0,1].set_title('Top 10 States by Car Sales')
axes[0,1].set_xlabel('State')
axes[0,1].set_ylabel('Cars Sold')

# ---------------------------------------------
# 3. Selling Price vs Odometer
# ---------------------------------------------

axes[1,0].scatter(
    df_car_prices['odometer'],
    df_car_prices['sellingprice'],
    alpha=0.3
)

axes[1,0].set_title('Selling Price vs Odometer')
axes[1,0].set_xlabel('Odometer')
axes[1,0].set_ylabel('Selling Price')

# ---------------------------------------------
# 4. Top 10 Car Brands
# ---------------------------------------------

top_brands = df_car_prices['make'].value_counts().head(10)

"""Project Summary
Newer = Higher Value: Fresh models fetch top dollar as age naturally erodes car value.

Regional Hotspots: Sales volume is concentrated in specific states backed by massive buyer demand.

Mileage Penalties: The data confirms that higher odometer numbers reliably shrink price tags.

Market Favorites: A handful of popular brands make up the bulk of the resale inventory.

The Pricing Formula: Age, mileage, brand, and condition are the primary pillars of used car valuation.

Data-Driven Decisions: This dashboard equips buyers and sellers with the market insights needed to optimize transaction timing and pricing strategies.

Project Summary
This project utilizes Python (Pandas, Matplotlib, and Seaborn) to clean, analyze, and visualize used car sales data.

Key Methodologies:

Data Prep: Streamlined data quality by addressing missing values and eliminating duplicates.

EDA & Dashboards: Built analytical visualizations to uncover core market trends.

Major Takeaways:

Vehicle pricing is heavily dictated by age, condition, and mileage (higher mileage directly correlates with lower prices).

Market volume is highly concentrated around specific brands and geographic regions.

This repository highlights practical expertise in exploratory data analysis and visual storytelling.
"""

